# Generated by Django 5.1.12 on 2025-10-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedispatchitem',
            name='dispatch_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_dispatch_item', to='purchase.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchasedispatchitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_shipment', to='purchase.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseshipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_shipment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasedispatchitem',
            name='purchase_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_dispatch_item', to='logistics.purchaseshipment'),
        ),
    ]
