# Generated by Django 5.1.8 on 2025-05-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('invoice_type', models.CharField(choices=[('', 'All'), ('OPD', 'Outpatient'), ('IPD', 'Inpatient'), ('Emergency', 'Emergency')], default='OPD', max_length=10)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient')], max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('consultation_type', models.CharField(choices=[('Initial', 'Initial'), ('Follow-Up', 'Follow-Up'), ('Specialist', 'Specialist')], default='Follow-Up', max_length=50)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review')], max_length=100, null=True)),
                ('service_date', models.DateField()),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review')], max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField()),
                ('triage_level', models.CharField(choices=[('1', 'Level 1 - Resuscitation'), ('2', 'Level 2 - Emergent'), ('3', 'Level 3 - Urgent'), ('4', 'Level 4 - Semi-Urgent'), ('5', 'Level 5 - Non-Urgent')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=50)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=50)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=50)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('charge_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile', 'Mobile Payment')], default='Cash', max_length=50)),
                ('payment_type', models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Lab', 'Lab Test'), ('Medicine', 'Medicine'), ('Ward', 'Ward'), ('OT', 'OT Bill'), ('Misc', 'Miscellaneous'), ('Advance', 'Advance'), ('Full', 'Full Bill Payment')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_stayed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
