# Generated by Django 5.1.8 on 2025-05-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_initial'),
        ('billing', '0001_initial'),
        ('core', '0002_initial'),
        ('facilities', '0002_initial'),
        ('inventory', '0001_initial'),
        ('lab_tests', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipd_invoices', to='patients.patientadmission'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_billing', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_fees', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_bills', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='doctorpayment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='doctorservicelog',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='doctorservicelog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='doctorservicelog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='billing.doctorpayment'),
        ),
        migrations.AddField(
            model_name='doctorservicerate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='treated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_bills', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtest'),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_bills', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_bills', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='otbill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_bills', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='otbill',
            name='operation_theatre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.operationtheatre'),
        ),
        migrations.AddField(
            model_name='otbill',
            name='ot_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ot_bill', to='facilities.otbooking'),
        ),
        migrations.AddField(
            model_name='otbill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_facility', to='facilities.bed'),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_bills', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='patient_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientadmission'),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_facility', to='facilities.room'),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_facility', to='facilities.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorservicerate',
            unique_together={('doctor', 'service_type')},
        ),
    ]
