# Generated by Django 5.1.8 on 2025-05-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consultationbill',
            unique_together={('invoice', 'appointment')},
        ),
    ]
