# Generated by Django 5.1.8 on 2025-05-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_consultationbill_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorpayment',
            old_name='total_amount',
            new_name='total_due_amount',
        ),
        migrations.AddField(
            model_name='doctorpayment',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='invoice_type',
            field=models.CharField(choices=[('', 'All'), ('OPD', 'Outpatient'), ('IPD', 'Inpatient'), ('Emergency', 'Emergency'), ('External-Lab-Test', 'External Lab Test patient')], default='OPD', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorservicelog',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review'), ('Lab-Test-Report', 'Lab Test Report')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorservicerate',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review'), ('Lab Test', 'Lab Test'), ('External-Lab-Test', 'external Lab Test')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labtestbill',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicinebill',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency'), ('External-Lab-Test', 'External Lab Test')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Lab', 'Lab Test'), ('Medicine', 'Medicine'), ('Ward', 'Ward'), ('OT', 'OT Bill'), ('Misc', 'Miscellaneous'), ('Advance', 'Advance'), ('Full', 'Full Bill Payment'), ('External-Lab-Test', 'External Lab test')], max_length=50, null=True),
        ),
    ]
