# Generated by Django 5.1.8 on 2025-05-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_total_amount_doctorpayment_total_due_amount_and_more'),
        ('medical_records', '0002_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvisit',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergergency_medical_records', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='emergencyvisit',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergergency_visit_invoices', to='billing.billinginvoice'),
        ),
    ]
