# Generated by Django 5.1.12 on 2025-11-05 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorservicelog',
            name='doctor_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorservicelog',
            name='hospital_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorservicelog',
            name='share_type',
            field=models.CharField(blank=True, choices=[('percent', '%'), ('fixed', 'Fixed')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctorservicelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorservicerate',
            name='doctor_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='doctorservicerate',
            name='hospital_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='doctorservicerate',
            name='share_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorservicelog',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorservicelog',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor Surgery'), ('Consultation', 'Consultation'), ('Followup-Consultation', 'Followup Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review'), ('Lab-Test-Report', 'Lab Test Report'), ('Physiotherapy', 'Physiotherapy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorservicerate',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor Surgery'), ('Consultation', 'Consultation'), ('Followup-Consultation', 'Followup Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review'), ('Lab-Test-Report', 'Lab Test Report'), ('Physiotherapy', 'Physiotherapy')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ReferralCommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=30)),
                ('service_id', models.PositiveIntegerField(blank=True, null=True)),
                ('service_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billinginvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_type', models.CharField(blank=True, choices=[('internal_doctor', 'Internal Doctor'), ('external_doctor', 'External Doctor'), ('agent', 'Marketing Agent'), ('hospital', 'Hospital/Clinic'), ('self', 'Self/Walk-in'), ('other', 'Other')], max_length=30, null=True)),
                ('external_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('bKash', 'bKash'), ('Other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('applied_referrals', models.ManyToManyField(blank=True, related_name='referral_payments', to='billing.referralcommissiontransaction')),
                ('referral_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.referralsource')),
            ],
        ),
        migrations.AddField(
            model_name='referralcommissiontransaction',
            name='referral_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to='billing.referralsource'),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='referral_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_source_invoices', to='billing.referralsource'),
        ),
        migrations.CreateModel(
            name='ReferralCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_type', models.CharField(blank=True, choices=[('internal_doctor', 'Internal Doctor'), ('external_doctor', 'External Doctor'), ('agent', 'Marketing Agent'), ('hospital', 'Hospital/Clinic'), ('self', 'Self/Walk-in'), ('other', 'Other')], max_length=30, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('surgery', 'Surgery'), ('emergency', 'Emergency visit'), ('physio', 'Physiotherapy'), ('ward', 'ward bill'), ('medicine', 'medicine bill'), ('all', 'All services'), ('other', 'Other')], max_length=30, null=True)),
                ('commission_type', models.CharField(choices=[('percent', '%'), ('fixed', 'Fixed')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apply_once_per_patient', models.BooleanField(default=True)),
                ('referral_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_commission_rules', to='billing.referralsource')),
            ],
            options={
                'unique_together': {('referral_source', 'service_type', 'commission_type')},
            },
        ),
    ]
