# Generated by Django 5.1.8 on 2025-05-11 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_patient_type'),
        ('billing', '0005_emergencyvisit_medical_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_invoices', to='appointments.appointment'),
        ),
    ]
