# Generated by Django 5.1.12 on 2025-11-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_doctorservicelog_doctor_share_and_more'),
        ('facilities', '0002_initial'),
        ('medical_records', '0002_initial'),
        ('patients', '0002_patient_referral_source_alter_patient_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestbill',
            name='user',
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='locked_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billinginvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Followup_Consultation', 'Follow-up Consultation'), ('Consultation_Discount', 'Consultation Discount'), ('Emergency', 'Emergency Service')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultationbill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='assigned_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_beds', to='facilities.bed'),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='discharge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency Service')], default='Emergency', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Lab_Test', 'Lab / Diagnostic Test'), ('Radiology', 'Radiology / Imaging (X-ray, USG, CT, MRI)'), ('ECG', 'ECG / EEG / EMG'), ('Procedure', 'Minor Procedures')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtestbill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Medicine_Sale', 'Medicine / Pharmacy Sale'), ('Injection', 'Injection / IV / Medication Service')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Blood_Bank', 'Blood Bank Services'), ('Vaccination', 'Vaccination'), ('Dental', 'Dental Services'), ('ENT', 'ENT Procedures'), ('Eye', 'Eye / Ophthalmology Procedures'), ('Hospital_Package', 'Hospital Packages'), ('Nursing', 'Nursing Service Charge'), ('Dialysis', 'Dialysis Charge'), ('Ambulance', 'Ambulance Charge'), ('Physiotherapy', 'Physiotherapy')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='miscellaneousbill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='otbill',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='otbill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='otbill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='otbill',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Operation_Theatre', 'Operation Theatre Charges'), ('Surgery', 'Surgical Charges'), ('OT_Consumables', 'OT Consumables')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='otbill',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='otbill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='ait_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Ward_Bed', 'Ward / Bed Charge'), ('Cabin', 'Cabin Charge'), ('ICU', 'ICU Charges'), ('CCU', 'CCU Charges'), ('NICU', 'NICU Charges'), ('PICU', 'PICU Charges')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardbill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='invoice_type',
            field=models.CharField(choices=[('', 'All'), ('OPD', 'Outpatient'), ('IPD', 'Inpatient'), ('Emergency', 'Emergency'), ('External-Lab-Test', 'External Lab Test patient'), ('Medicine-Sale-Only', 'Medicine Sale Only'), ('Other-Services', 'Other services')], default='OPD', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoice_records', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_billing', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency'), ('Medicine-Only', 'Medicine Only'), ('Other-Services', 'Other services')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultationbill',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyvisit',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_visit_invoice', to='billing.billinginvoice'),
        ),
        migrations.AlterField(
            model_name='emergencyvisit',
            name='triage_level',
            field=models.CharField(choices=[('1', 'Level 1 - Revival'), ('2', 'Level 2 - Emergent'), ('3', 'Level 3 - Urgent'), ('4', 'Level 4 - Semi-Urgent'), ('5', 'Level 5 - Non-Urgent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='miscellaneousbill',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='miscellaneousbill',
            name='service_name',
            field=models.CharField(choices=[('Blood_Bank', 'Blood Bank Services'), ('Vaccination', 'Vaccination'), ('Dental', 'Dental Services'), ('ENT', 'ENT Procedures'), ('Eye', 'Eye / Ophthalmology Procedures'), ('Hospital_Package', 'Hospital Packages'), ('Nursing', 'Nursing Service Charge'), ('Dialysis', 'Dialysis Charge'), ('Ambulance', 'Ambulance Charge'), ('Physiotherapy', 'Physiotherapy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='miscellaneousbill',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='otbill',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wardbill',
            name='days_stayed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardbill',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
    ]
