# Generated by Django 5.1.12 on 2025-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_labtestbill_user_billinginvoice_ait_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinebill',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='dosage_schedule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
