# Generated by Django 5.1.8 on 2025-05-12 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_billinginvoice_appointment'),
        ('medical_records', '0004_medicalrecord_external_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_invoice_records', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='medicinebill',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='invoice_type',
            field=models.CharField(choices=[('', 'All'), ('OPD', 'Outpatient'), ('IPD', 'Inpatient'), ('Emergency', 'Emergency'), ('External-Lab-Test', 'External Lab Test patient'), ('Medicine-Sale-Only', 'Medicine Sale Only')], default='OPD', max_length=50),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency'), ('Medicine-Only', 'Medicine Only')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labtestbill',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Delivered', 'Delivered')], default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicinebill',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Delivered', 'Delivered')], default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency'), ('External-Lab-Test', 'External Lab Test'), ('Medicine-Only', 'Medicine Only')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Lab', 'Lab Test'), ('Medicine', 'Medicine'), ('Ward', 'Ward'), ('OT', 'OT Bill'), ('Misc', 'Miscellaneous'), ('Advance', 'Advance'), ('Full', 'Full Bill Payment'), ('External-Lab-Test', 'External Lab test'), ('Medicine-Sale-Only', 'Medicine Sale Only')], max_length=50, null=True),
        ),
    ]
