# Generated by Django 5.1.12 on 2025-11-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_medicinebill_dosage_medicinebill_dosage_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcommissionrule',
            name='service_type',
            field=models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('lab', 'Lab Test'), ('surgery', 'Surgery'), ('ot', 'Operation Theatre'), ('emergency', 'Emergency visit'), ('physio', 'Physiotherapy'), ('ward', 'ward bill'), ('medicine', 'medicine bill'), ('all', 'All services'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
