# Generated by Django 5.1.8 on 2025-05-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billinginvoice_user_consultationbill_user_and_more'),
        ('medical_records', '0006_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorservicelog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_service_logs', to='billing.billinginvoice'),
        ),
        migrations.AddField(
            model_name='doctorservicelog',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.medicalrecord'),
        ),
    ]
