# Generated by Django 5.1.12 on 2025-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_referralcommissionrule_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorservicerate',
            name='hospital_share',
        ),
        migrations.AlterField(
            model_name='doctorservicelog',
            name='surgery_type',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor Surgery'), ('Major', 'Major'), ('OT-Procedure', 'OT Procedure'), ('Emergency', 'Emergency Surgery')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorservicerate',
            name='surgery_type',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor Surgery'), ('Major', 'Major'), ('OT-Procedure', 'OT Procedure'), ('Emergency', 'Emergency Surgery')], max_length=100, null=True),
        ),
    ]
