# Generated by Django 5.1.8 on 2025-05-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_doctorservicelog_invoice_and_more'),
        ('medical_records', '0007_remove_prescription_appointment'),
        ('patients', '0005_remove_patientadmission_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginvoice',
            name='admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_admission', to='patients.patientadmission'),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_medical_record', to='medical_records.medicalrecord'),
        ),
    ]
