# Generated by Django 5.1.12 on 2025-11-24 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_doctorservicerate_hospital_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorservicelog',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
