# Generated by Django 5.1.8 on 2025-05-18 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_billinginvoice_admission_and_more'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginvoice',
            name='appointment',
        ),
        migrations.AddField(
            model_name='doctorpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile', 'Mobile Payment')], default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorpayment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
    ]
