# Generated by Django 5.1.12 on 2025-11-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_doctorservicelog_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorservicelog',
            name='payment',
        ),
        migrations.AddField(
            model_name='doctorpayment',
            name='applied_service_logs',
            field=models.ManyToManyField(blank=True, related_name='service_log_payments', to='billing.doctorservicelog'),
        ),
    ]
