# Generated by Django 5.1.8 on 2025-05-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_billinginvoice_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile', 'Mobile Payment')], default='Cash', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpayment',
            name='total_due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpayment',
            name='total_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
