# Generated by Django 5.1.12 on 2025-11-28 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_remove_doctorservicelog_payment_and_more'),
        ('lab_tests', '0007_externallabvisit_lab_test_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestbill',
            name='lab_test_request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_requests', to='lab_tests.labtestrequest'),
        ),
    ]
