# Generated by Django 5.1.12 on 2025-11-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_labtestbill_lab_test_request_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestbill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
