# Generated by Django 5.1.8 on 2025-05-20 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_labtestbill_lab_test_catelogue'),
        ('lab_tests', '0006_remove_labtestrequest_lab_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestbill',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtest'),
        ),
    ]
