# Generated by Django 5.1.12 on 2025-12-01 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_alter_labtestbill_ait_amount_and_more'),
        ('patients', '0003_dischargereport_patient_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardbill',
            name='patient_emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_wards', to='billing.emergencyvisit'),
        ),
        migrations.AlterField(
            model_name='wardbill',
            name='patient_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_ward', to='patients.patientadmission'),
        ),
    ]
