# Generated by Django 5.1.12 on 2025-12-02 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_wardbill_patient_emergency_and_more'),
        ('facilities', '0004_alter_otbooking_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvisit',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_rooms', to='facilities.room'),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='assigned_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_wards', to='facilities.ward'),
        ),
    ]
