# Generated by Django 5.1.12 on 2025-12-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_emergencyvisit_assigned_room_and_more'),
        ('facilities', '0004_alter_otbooking_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardbill',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_facility', to='facilities.ward'),
        ),
    ]
