# Generated by Django 5.1.12 on 2025-12-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_wardbill_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyvisit',
            name='is_discharged',
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='admission_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='bed_assignment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred')], default='Admitted', max_length=20),
        ),
    ]
