# Generated by Django 5.1.12 on 2025-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_remove_emergencyvisit_is_discharged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvisit',
            name='discharge_approved',
            field=models.BooleanField(default=False),
        ),
    ]
