# Generated by Django 5.1.12 on 2025-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_emergencyvisit_discharge_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardbill',
            name='charge_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wardbill',
            name='charge_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
