# Generated by Django 5.1.12 on 2025-12-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_wardbill_charge_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvisit',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyvisit',
            name='is_converted_to_admission',
            field=models.BooleanField(default=False),
        ),
    ]
