# Generated by Django 5.1.12 on 2025-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_emergencyvisit_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyvisit',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('Emergency-Service', 'Emergency Service')], default='Emergency-Service', max_length=20),
        ),
    ]
