# Generated by Django 5.1.12 on 2025-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_emergencyvisit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorservicelog',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor Surgery'), ('Consultation', 'Consultation'), ('Followup-Consultation', 'Followup Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review'), ('Lab-Test-Report', 'Lab Test Report'), ('Physiotherapy', 'Physiotherapy'), ('Anesthesia-Service', 'Anesthesia Service')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorservicerate',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Minor', 'Minor Surgery'), ('Consultation', 'Consultation'), ('Followup-Consultation', 'Followup Consultation'), ('Surgery', 'Surgery'), ('Lab Review', 'Lab Review'), ('Lab-Test-Report', 'Lab Test Report'), ('Physiotherapy', 'Physiotherapy'), ('Anesthesia-Service', 'Anesthesia Service')], max_length=100, null=True),
        ),
    ]
