# Generated by Django 5.1.12 on 2025-12-07 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_alter_doctorservicelog_service_type_and_more'),
        ('facilities', '0005_otbookingprocedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otbill',
            name='ot_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ot_bill', to='facilities.otbooking'),
        ),
    ]
