# Generated by Django 5.1.12 on 2025-12-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_otbill_ot_booking'),
        ('facilities', '0006_bed_created_at_bed_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otbill',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='facilities.otbookingprocedure'),
        ),
    ]
