# Generated by Django 5.1.12 on 2025-10-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(default='None', max_length=100)),
                ('dosage_schedule', models.CharField(blank=True, choices=[('1+0+1', '1+0+1'), ('1+1+0', '1+1+0'), ('1+1+1', '1+1+1'), ('0+1+1', '0+1+1'), ('0+1+0', '0+1+0'), ('0+0+1', '0+0+1'), ('1+0+0', '1+0+0'), ('Every-4-Hours', 'Every 4 Hours'), ('Every-6-Hours', 'Every 6 Hours'), ('Every-8-Hours', 'Every 8 Hours'), ('Every-12-Hours', 'Every 12 Hours'), ('Every-24-Hours', 'Every 24 Hours'), ('As Needed', 'As Needed')], max_length=50, null=True)),
                ('medication_duration', models.IntegerField(blank=True, null=True)),
                ('UOM', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('external_doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.TextField(default='N/A')),
                ('treatment_plan', models.TextField(default='N/A')),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='core.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_records', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_progress_notes', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='medical_records.medicalrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_progress_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
