# Generated by Django 5.1.8 on 2025-05-01 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='core.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_schedule', models.CharField(blank=True, choices=[('1+0+1', '1+0+1'), ('1+1+0', '1+1+0'), ('1+1+1', '1+1+1'), ('0+1+1', '0+1+1'), ('0+1+0', '0+1+0'), ('0+0+1', '0+0+1'), ('1+0+0', '1+0+0'), ('Every-4-Hours', 'Every 4 Hours'), ('Every-6-Hours', 'Every 6 Hours'), ('Every-8-Hours', 'Every 8 Hours'), ('Every-12-Hours', 'Every 12 Hours'), ('Every-24-Hours', 'Every 24 Hours'), ('As Needed', 'As Needed')], max_length=50, null=True)),
                ('medication_duration', models.IntegerField(blank=True, null=True)),
                ('UOM', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient')], max_length=50, null=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_prescriptions', to='appointments.appointment')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_prescriptions', to='medical_records.medicalrecord')),
                ('medication_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_category', to='inventory.productcategory')),
                ('medication_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_names', to='inventory.product')),
                ('medication_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_types', to='inventory.producttype')),
            ],
        ),
    ]
