# Generated by Django 5.1.12 on 2025-12-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servicetaxpolicy_name'),
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecordprogress',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_proggress_records', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecordprogress'),
        ),
    ]
