# Generated by Django 5.1.12 on 2025-12-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_medicalrecordprogress_doctor_prescription_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_pulse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_spo2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vital_temp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
