# Generated by Django 5.1.8 on 2025-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_alter_prescription_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='external_doctor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(default='N/A'),
        ),
    ]
