# Generated by Django 5.1.8 on 2025-05-12 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_patient_type'),
        ('medical_records', '0004_medicalrecord_external_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_medical_record', to='appointments.appointment'),
        ),
    ]
