# Generated by Django 5.1.8 on 2025-05-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_medicalrecord_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
    ]
