# Generated by Django 5.1.8 on 2025-05-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
    ]
