# Generated by Django 5.1.8 on 2025-05-17 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicinesaleonly_medicinesaleitem'),
        ('medical_records', '0007_remove_prescription_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='additional_instructions',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='UOM',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage_schedule',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_category',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_duration',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication_type',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecord'),
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(default='None', max_length=100)),
                ('dosage_schedule', models.CharField(blank=True, choices=[('1+0+1', '1+0+1'), ('1+1+0', '1+1+0'), ('1+1+1', '1+1+1'), ('0+1+1', '0+1+1'), ('0+1+0', '0+1+0'), ('0+0+1', '0+0+1'), ('1+0+0', '1+0+0'), ('Every-4-Hours', 'Every 4 Hours'), ('Every-6-Hours', 'Every 6 Hours'), ('Every-8-Hours', 'Every 8 Hours'), ('Every-12-Hours', 'Every 12 Hours'), ('Every-24-Hours', 'Every 24 Hours'), ('As Needed', 'As Needed')], max_length=50, null=True)),
                ('medication_duration', models.IntegerField(blank=True, null=True)),
                ('UOM', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('medication_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory')),
                ('medication_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('medication_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medical_records.prescription')),
            ],
        ),
    ]
