# Generated by Django 5.1.12 on 2025-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(choices=[('Consultation', 'Consultation'), ('Followup_Consultation', 'Follow-up Consultation'), ('Lab_Test', 'Lab / Diagnostic Test'), ('Radiology', 'Radiology / Imaging (X-ray, USG, CT, MRI)'), ('ECG', 'ECG / EEG / EMG'), ('Procedure', 'Minor Procedures'), ('Operation_Theatre', 'Operation Theatre Charges'), ('Surgery', 'Surgical Charges'), ('Ward_Bed', 'Ward / Bed Charge'), ('Cabin', 'Cabin Charge'), ('ICU', 'ICU Charges'), ('CCU', 'CCU Charges'), ('NICU', 'NICU Charges'), ('PICU', 'PICU Charges'), ('OT_Consumables', 'OT Consumables'), ('Medicine_Sale', 'Medicine / Pharmacy Sale'), ('Injection', 'Injection / IV / Medication Service'), ('Nursing', 'Nursing Service Charge'), ('Emergency', 'Emergency Service'), ('Ambulance', 'Ambulance Charge'), ('Dialysis', 'Dialysis Charge'), ('Physiotherapy', 'Physiotherapy'), ('Blood_Bank', 'Blood Bank Services'), ('Vaccination', 'Vaccination'), ('Dental', 'Dental Services'), ('ENT', 'ENT Procedures'), ('Eye', 'Eye / Ophthalmology Procedures'), ('Consultation_Discount', 'Consultation Discount'), ('Hospital_Package', 'Hospital Packages')], max_length=100, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive'), ('exempt', 'Exempt')], default='exempt', max_length=20)),
                ('ait_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ait_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive'), ('exempt', 'Exempt')], default='exempt', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('policy_code', models.CharField(blank=True, max_length=40, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=15)),
                ('ait_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ait_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
