# Generated by Django 5.1.12 on 2025-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicetaxpolicy_taxpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetaxpolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
