# Generated by Django 5.1.12 on 2025-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
    ]
