# Generated by Django 5.1.8 on 2025-05-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDepreciationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depreciation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='finance.asset')),
            ],
        ),
    ]
