# Generated by Django 5.1.12 on 2025-10-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_invoices', to='logistics.purchaseshipment'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceattachment',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_attachment', to='finance.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payment_invoice', to='finance.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasepaymentattachment',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payment_attachment', to='finance.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchasepaymentattachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
