# Generated by Django 5.1.12 on 2025-11-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allexpenses',
            name='expense_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
