

MEDICINE_CATEGORY_CHOICES = [
    ('Analgesics', 'Analgesics (Pain Relievers)'),
    ('Antipyretics', 'Antipyretics (Fever Reducers)'),
    ('Antibiotics', 'Antibiotics'),
    ('Antiseptics', 'Antiseptics'),
    ('Antidepressants', 'Antidepressants'),
    ('Antidiabetics', 'Antidiabetics'),
    ('Antihistamines', 'Antihistamines (Allergy Medications)'),
    ('Antihypertensives', 'Antihypertensives (Blood Pressure Medications)'),
    ('Anticoagulants', 'Anticoagulants (Blood Thinners)'),
    ('Antifungals', 'Antifungals'),
    ('Antivirals', 'Antivirals'),
    ('Bronchodilators', 'Bronchodilators (Asthma/COPD Medications)'),
    ('Corticosteroids', 'Corticosteroids'),
    ('Diuretics', 'Diuretics'),
    ('Gastrointestinal', 'Gastrointestinal Medications'),
    ('Hormonal', 'Hormonal Medications'),
    ('Immunosuppressants', 'Immunosuppressants'),
    ('Muscle Relaxants', 'Muscle Relaxants'),
    ('Neurological', 'Neurological Medications'),
    ('Ophthalmic', 'Ophthalmic Medications (Eye Drops)'),
    ('Psychotropic', 'Psychotropic Medications'),
    ('Sedatives', 'Sedatives & Hypnotics'),
    ('Vaccines', 'Vaccines'),
    ('Vitamins', 'Vitamins & Supplements'),
    ('Others', 'Others'),
]