# Generated by Django 5.1.12 on 2025-10-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, max_length=10, null=True)),
                ('daily_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override for this specific bed', max_digits=10, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('bed_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Oxygen', 'Oxygen'), ('Ventilator', 'Ventilator')], max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationTheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('ot_type', models.CharField(blank=True, choices=[('General', 'General Surgery'), ('Cardiac', 'Cardiac OT'), ('Neuro', 'Neurosurgery OT'), ('Other', 'Other')], default='General', max_length=50, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per hour for using this OT', max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OTBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_start', models.DateTimeField(blank=True, null=True)),
                ('booked_end', models.DateTimeField(blank=True, null=True)),
                ('surgery_type', models.CharField(blank=True, choices=[('Minor', 'Minor Surgery'), ('Major', 'Major Surgery'), ('OT-Procedure', 'OT Procedure'), ('Emergency', 'Emergency Surgery')], max_length=100, null=True)),
                ('patient_type', models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('Emergency', 'Emergency')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Room No.')),
                ('room_type', models.CharField(choices=[('Private', 'Private Room'), ('Semi-Private', 'Semi-Private Room'), ('Suite', 'Suite')], max_length=20)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='How many beds fit in this room', null=True)),
                ('daily_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Daily charge for using this room', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('General', 'General Ward'), ('Private', 'Private Room'), ('SemiPrivate', 'Semi Private'), ('ICU', 'ICU'), ('SDU', 'Step-Down Unit'), ('NICU', 'Neonatal ICU'), ('PICU', 'Pediatric ICU')], max_length=50)),
                ('daily_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BedAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_move', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.bed')),
            ],
        ),
    ]
