# Generated by Django 5.1.12 on 2025-11-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_labtestbill_user_billinginvoice_ait_amount_and_more'),
        ('facilities', '0002_initial'),
        ('patients', '0003_dischargereport_patient_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otbooking',
            name='surgery_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='daily_charge',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='daily_charge',
        ),
        migrations.AddField(
            model_name='bed',
            name='hourly_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bedassignmenthistory',
            name='emergency_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_bed_histories', to='billing.emergencyvisit'),
        ),
        migrations.AddField(
            model_name='otbooking',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Followup_Consultation', 'Follow-up Consultation'), ('Lab_Test', 'Lab / Diagnostic Test'), ('Radiology', 'Radiology / Imaging (X-ray, USG, CT, MRI)'), ('ECG', 'ECG / EEG / EMG'), ('Procedure', 'Minor Procedures'), ('Operation_Theatre', 'Operation Theatre Charges'), ('Surgery', 'Surgical Charges'), ('Ward_Bed', 'Ward / Bed Charge'), ('Cabin', 'Cabin Charge'), ('ICU', 'ICU Charges'), ('CCU', 'CCU Charges'), ('NICU', 'NICU Charges'), ('PICU', 'PICU Charges'), ('OT_Consumables', 'OT Consumables'), ('Medicine_Sale', 'Medicine / Pharmacy Sale'), ('Injection', 'Injection / IV / Medication Service'), ('Nursing', 'Nursing Service Charge'), ('Emergency', 'Emergency Service'), ('Ambulance', 'Ambulance Charge'), ('Dialysis', 'Dialysis Charge'), ('Physiotherapy', 'Physiotherapy'), ('Blood_Bank', 'Blood Bank Services'), ('Vaccination', 'Vaccination'), ('Dental', 'Dental Services'), ('ENT', 'ENT Procedures'), ('Eye', 'Eye / Ophthalmology Procedures'), ('Consultation_Discount', 'Consultation Discount'), ('Hospital_Package', 'Hospital Packages')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Oxygen', 'Oxygen'), ('Ventilator', 'Ventilator'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='daily_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bedassignmenthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_histories', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('General', 'General Room'), ('Cabin', 'Cabin / Private Room'), ('SemiPrivate', 'Semi-Private Room'), ('Suite', 'Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(choices=[('General', 'General Ward'), ('Private', 'Private Room'), ('SemiPrivate', 'Semi Private'), ('ICU', 'ICU'), ('SDU', 'Step-Down Unit'), ('NICU', 'Neonatal ICU'), ('PICU', 'Pediatric ICU'), ('Emergency', 'Emergency ward')], max_length=50),
        ),
    ]
