# Generated by Django 5.1.8 on 2025-05-14 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_doctorservicelog_invoice_and_more'),
        ('facilities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otbooking',
            name='procedure_name',
        ),
        migrations.AddField(
            model_name='otbooking',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.doctorservicerate'),
        ),
    ]
