# Generated by Django 5.1.8 on 2025-05-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_remove_otbooking_procedure_name_otbooking_procedure'),
        ('patients', '0005_remove_patientadmission_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedassignmenthistory',
            name='patient_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='patients.patientadmission'),
        ),
    ]
