# Generated by Django 5.1.12 on 2025-12-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_emergencyvisit_status'),
        ('core', '0005_alter_servicetaxpolicy_name'),
        ('facilities', '0004_alter_otbooking_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTBookingProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('ot_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='facilities.otbooking')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_procedures', to='billing.doctorservicerate')),
            ],
        ),
    ]
