# Generated by Django 5.1.12 on 2025-11-21 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankaccount'),
        ('inventory', '0004_medicinesaleitem_category_and_more'),
        ('product', '0004_alter_producttype_name'),
        ('purchase', '0002_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('advance_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('AIT_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Overall AIT (%)', max_digits=5, null=True)),
                ('AIT_type', models.CharField(blank=True, choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ait_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Write custom terms & conditions for this invoice', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('UPDATED', 'Updated'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('is_goods_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_invoice_supplier', to='supplier.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectPurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('raw_materials', 'raw_materials'), ('finished_product', 'finished_product'), ('component', 'component'), ('BOM', 'BOM')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('confirmed_quantity', models.FloatField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14)),
                ('VAT_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VAT_type', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', max_length=20)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase_invoice_batches', to='purchase.batch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase_items', to='purchase.directpurchaseinvoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchase_invoice_items', to='product.product')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ait_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CREDIT', 'Credit / Accounts Payable')], default='CASH', max_length=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('asset_tag', models.CharField(blank=True, help_text='Asset identifier if product is equipment/furniture', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='purchase.directpurchaseinvoice')),
                ('supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_payment_supplier', to='supplier.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Payment',
                'verbose_name_plural': 'Purchase Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.batch')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_items', to='purchase.directpurchaseinvoiceitem')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_received_items', to='purchase.directpurchaseinvoice')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('invoice_item', 'warehouse', 'location', 'batch')},
            },
        ),
    ]
