# Generated by Django 5.1.12 on 2025-11-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('parent', 'Parent'), ('staff', 'Staff'), ('superadmin', 'SuperAdmin'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('nurse', 'Nurse'), ('engineer', 'Engineer'), ('general', 'General')], default='General', max_length=15),
        ),
    ]
