# Generated by Django 5.1.8 on 2025-05-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billinginvoice_medical_record_and_more'),
        ('core', '0002_initial'),
        ('inventory', '0001_initial'),
        ('medical_records', '0004_medicalrecord_external_doctor_and_more'),
        ('patients', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSaleOnly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='medicine_only_prescriptions/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_only_doctors', to='core.doctor')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_only_invoices', to='billing.billinginvoice')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_only_medical_records', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('medicine_sale_only', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.medicinesaleonly')),
            ],
        ),
    ]
