# Generated by Django 5.1.12 on 2025-10-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_transactions', to='purchase.purchaseorder'),
        ),
    ]
