# Generated by Django 5.1.12 on 2025-11-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_doctorservicelog_doctor_share_and_more'),
        ('inventory', '0003_inventorytransaction_purchase_order'),
        ('product', '0003_product_is_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinesaleitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='medicinesaleonly',
            name='referral_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.referralsource'),
        ),
    ]
