# Generated by Django 5.1.12 on 2025-10-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_initial'),
        ('core', '0002_initial'),
        ('lab_tests', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallabvisit',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_lab_visit_medical_records', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='externallabvisit',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests_medical_records', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtestcatalog'),
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtestcategory'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests_requests', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='labtestrequestitem',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtestcatalog'),
        ),
        migrations.AddField(
            model_name='labtestrequestitem',
            name='labtest_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='lab_tests.labtestrequest'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='test_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtestcatalog'),
        ),
        migrations.AddField(
            model_name='labtestresultorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lab_tests', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='labtestresultorder',
            name='lab_test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_result_order', to='lab_tests.labtestrequest'),
        ),
        migrations.AddField(
            model_name='labtestresultorder',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='labtestresultorder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lab_tests', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='labtestresultorder',
            name='test_assistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labtest_assistance', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='labtestresultorder',
            name='test_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labtest_doctor', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='result_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab_tests.labtestresultorder'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestitem',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtestcatalog'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestrequest',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_labtest', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestrequest',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_lab_test_groups', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestrequest',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestitem',
            name='suggested_labtest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_items', to='lab_tests.suggestedlabtestrequest'),
        ),
    ]
