# Generated by Django 5.1.8 on 2025-05-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('lab_tests', '0001_initial'),
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labtestresult',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labtestresultorder',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'Inpatient'), ('OPD', 'OutPatient'), ('External-Lab-Test', 'External Lab Test'), ('Emergency', 'Emergency')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ExternalLabVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='external_prescriptions/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_test_doctors', to='core.doctor')),
                ('medical_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_lab_visit', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
