# Generated by Django 5.1.12 on 2025-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestcategory',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Lab_Test', 'Lab / Diagnostic Test'), ('Radiology', 'Radiology / Imaging (X-ray, USG, CT, MRI)'), ('ECG', 'ECG / EEG / EMG'), ('Procedure', 'Minor Procedures')], max_length=50, null=True),
        ),
    ]
