# Generated by Django 5.1.8 on 2025-05-10 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_emergencyvisit_medical_record_and_more'),
        ('lab_tests', '0002_alter_labtest_patient_type_and_more'),
        ('medical_records', '0002_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallabvisit',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_lab_visit_invoices', to='billing.billinginvoice'),
        ),
        migrations.AlterField(
            model_name='externallabvisit',
            name='medical_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_lab_visit_medical_records', to='medical_records.medicalrecord'),
        ),
    ]
