# Generated by Django 5.1.12 on 2025-11-20 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0004_labtestcatalog_created_at_labtestcatalog_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sample_type', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Stool', 'Stool'), ('Sputum', 'Sputum'), ('Swab', 'Swab'), ('Other', 'Other')], max_length=50)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Collection'), ('collected', 'Collected'), ('received', 'Received in Lab'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to=settings.AUTH_USER_MODEL)),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_items', to='lab_tests.labtestrequestitem')),
                ('request_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lab_tests.labtestrequest')),
            ],
        ),
    ]
