# Generated by Django 5.1.8 on 2025-05-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0004_suggestedlabtestrequest'),
        ('medical_records', '0006_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests_medical_records', to='medical_records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
