# Generated by Django 5.1.8 on 2025-05-20 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('lab_tests', '0005_labtest_medical_record_labtest_price_and_more'),
        ('medical_records', '0009_medicalrecordprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestrequest',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='suggestedlabtestrequest',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='suggestedlabtestrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedlabtestrequest',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests_requests', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suggestedlabtestrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suggestedlabtestrequest',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_lab_test_groups', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='suggestedlabtestrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Partially Completed', 'Partially Completed'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='LabTestRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtestcatalog')),
                ('labtest_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='lab_tests.labtestrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedLabTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Requested', 'Requested'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_tests.labtestcatalog')),
                ('suggested_labtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_items', to='lab_tests.suggestedlabtestrequest')),
            ],
        ),
    ]
