# Generated by Django 5.1.12 on 2025-11-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0005_labsamplecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresultorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='lab_qr_codes/'),
        ),
    ]
