# Generated by Django 5.1.12 on 2025-11-28 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0006_labtestresultorder_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallabvisit',
            name='lab_test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_lab_tests', to='lab_tests.labtestrequest'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='requested_lab_test_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='suggestedlabtestrequest',
            name='suggested_lab_test_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
