# Generated by Django 5.1.8 on 2025-05-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_alter_appointment_patient_type'),
        ('lab_tests', '0006_remove_labtestrequest_lab_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestresultorder',
            name='lab_test_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_result_order', to='lab_tests.labtestrequest'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestrequest',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_labtest', to='appointments.appointment'),
        ),
    ]
