# Generated by Django 5.1.12 on 2025-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0007_externallabvisit_lab_test_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='external_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
