# Generated by Django 5.1.12 on 2025-12-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0008_labtestrequest_external_ref'),
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequestitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pres_lab_req_items', to='medical_records.prescription'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pres_lab_suggest_items', to='medical_records.prescription'),
        ),
    ]
