# Generated by Django 5.1.12 on 2025-12-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0031_appointment_invoice_alter_appointment_patient_type'),
        ('lab_tests', '0009_labtestrequestitem_prescription_and_more'),
        ('medical_records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_labtest_request', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecordprogress'),
        ),
        migrations.AddField(
            model_name='labtestrequestitem',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecordprogress'),
        ),
        migrations.AddField(
            model_name='labtestresult',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pres_lab_result_items', to='medical_records.prescription'),
        ),
        migrations.AddField(
            model_name='suggestedlabtestitem',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecordprogress'),
        ),
    ]
