# Generated by Django 5.1.12 on 2025-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
    ]
