# Generated by Django 5.1.8 on 2025-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD'), ('IPD', 'IPD')], max_length=20, null=True),
        ),
    ]
