# Generated by Django 5.1.8 on 2025-05-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_patient_type'),
        ('medical_records', '0006_remove_medicalrecord_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_record',
            field=models.ForeignKey(blank=True, help_text='Linked after first visit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_appointment', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD'), ('IPD', 'IPD')], max_length=20, null=True),
        ),
    ]
