# Generated by Django 5.1.8 on 2025-05-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_appointment_patient_type'),
        ('medical_records', '0007_remove_prescription_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record_appointments', to='medical_records.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
    ]
