# Generated by Django 5.1.12 on 2025-12-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_alter_appointment_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked', 'Checked'), ('Prescription-Given', 'Prescription Given'), ('Lab-Test-Requested', 'Lab Test Requested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Scheduled', 'Scheduled')], default='Pending', max_length=50),
        ),
    ]
