# Generated by Django 5.1.12 on 2025-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_appointment_created_at_appointment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD'), ('IPD', 'IPD')], max_length=20, null=True),
        ),
    ]
