# Generated by Django 5.1.12 on 2025-12-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_alter_appointment_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Follow-up', 'Follow up'), ('New', 'New')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
    ]
