# Generated by Django 5.1.12 on 2025-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_alter_appointment_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Follow-up', 'Follow up')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
    ]
