# Generated by Django 5.1.12 on 2025-12-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0030_alter_appointment_patient_type'),
        ('billing', '0025_otbill_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_appointments', to='billing.billinginvoice'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=20, null=True),
        ),
    ]
