# Generated by Django 5.1.12 on 2025-12-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0031_appointment_invoice_alter_appointment_patient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Follow-up', 'Follow up')], max_length=20, null=True),
        ),
    ]
