# Generated by Django 5.1.12 on 2025-12-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0032_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(blank=True, choices=[('Follow-up', 'Follow up'), ('New', 'New')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD'), ('IPD', 'IPD')], max_length=20, null=True),
        ),
    ]
