# Generated by Django 5.1.12 on 2026-01-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
