# Generated by Django 5.1.8 on 2025-05-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
