# Generated by Django 5.1.12 on 2025-11-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_labtestbill_user_billinginvoice_ait_amount_and_more'),
        ('patients', '0002_patient_referral_source_alter_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargereport',
            name='patient_emergency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_discharge_report', to='billing.emergencyvisit'),
        ),
    ]
