# Generated by Django 5.1.12 on 2025-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_dischargereport_patient_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='discharge_approved',
            field=models.BooleanField(default=False),
        ),
    ]
