# Generated by Django 5.1.8 on 2025-05-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_unique_patient_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientadmission',
            name='invoice',
        ),
    ]
