# Generated by Django 5.1.12 on 2025-12-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_emergencyvisit_discharge_approved'),
        ('patients', '0004_patientadmission_discharge_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargereport',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_discharge_report', to='billing.billinginvoice'),
        ),
    ]
