# Generated by Django 5.1.12 on 2025-12-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_dischargereport_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargereport',
            name='patient_admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_report', to='patients.patientadmission'),
        ),
    ]
