# Generated by Django 5.1.12 on 2025-12-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_emergencyvisit_end_time_and_more'),
        ('patients', '0006_alter_dischargereport_patient_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='emergency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.emergencyvisit'),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='admission_type',
            field=models.CharField(choices=[('Emergency', 'Emergency'), ('Planned', 'Planned'), ('Referral', 'Referral'), ('Emergency-To-IPD', 'Emergency to IPD')], default='Planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Transferred', 'Transferred'), ('Convert-To-IPD', 'Convert to IPD')], default='Admitted', max_length=20),
        ),
    ]
